app/Index/__init__.py
from flask import Blueprint


Index = Blueprint('Index', __name__, template_folder='templates', static_folder='static', static_url_path='/Index')

from . import routes

app/Index/routes.py
from . import Index
import os
from flask import render_template, redirect, url_for, request, jsonify
import requests
from ..config import DevelopmentConfig
import mysql.connector

# Borrar producto seleccionado
@Index.route('/borrar/<int:producto_id>', methods=['GET', 'POST'])
def borrar_producto(producto_id):
    try:
        # Intenta establecer una conexión y borrar el producto según su ID
        connection = connect_to_database()
        cursor = connection.cursor() 
        cursor.execute(f"SELECT Asset FROM Productos WHERE Id = {producto_id};")
        asset_model_path = cursor.fetchone()[0] # optiene el path de la modelo a borrar
        cursor.execute(f"SELECT Img, Id FROM Imagenes_de_Productos JOIN Imagenes ON Imagenes_de_Productos.Id_Img = Imagenes.Id WHERE Id_Productos = {producto_id};")
        asset_img_path = [path for path in cursor.fetchall()] # optiene el path del imagen a borrar
        cursor.execute(f"DELETE FROM Productos WHERE Id = {producto_id};")

        print(asset_img_path)

        # Borra el modelo y la imagen
        if asset_model_path:
            model_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..' ,'assets',asset_model_path)
            os.remove(model_path)
        if asset_img_path:
            for path in asset_img_path:
                cursor.execute(f"DELETE FROM Imagenes WHERE Id = {path[1]};")
                img_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..' ,'assets',path[0])
                print("path:", os.path.join(os.path.dirname(os.path.abspath(__file__)), '..' ,'assets',path[0]))
                os.remove(img_path)

        connection.commit()
    except Exception as e:
        print(str(e))
    finally:
        cursor.close()
        connection.close()
    
    # Redirige de vuelta a la página principal después de borrar
    return redirect(url_for('Index.index'))

# Vista principal
@Index.route('/', methods=['GET'])
def index():
    img_urls = []

    try:
        # Intentar establecer una conexión y realizar una operación simple en la base de datos
        connection = connect_to_database()
        cursor = connection.cursor() 
        cursor.execute("SELECT Productos.Id AS id, Productos.Nombre AS NombreProducto, Productos.Precio, MIN(Imagenes.Img) AS RutaImagen FROM Productos JOIN Imagenes_de_Productos ON Productos.Id = Imagenes_de_Productos.Id_Productos JOIN Imagenes ON Imagenes_de_Productos.Id_Img = Imagenes.Id GROUP BY Productos.Id;") 
        results = cursor.fetchall() 
        for result in results:
            img_urls.append({
                'Id': result[0],
                'NombreProducto': result[1],
                'Precio': result[2],
                'RutaImagen': url_for('assets_static', filename=result[3])
            })
    except Exception as e:
        print(str(e))
        img_urls.append('error')
    finally:
        cursor.close() # El cursor se finaliza
        connection.close() # Se finaliza la conexión
    return render_template('index.html', img_url=img_urls)

# Función para conectar a la base de datos
def connect_to_database():
    from .. import app
    return mysql.connector.connect(
        user=app.config['DB_USER'],
        password=app.config['DB_PASSWORD'],
        host=app.config['DB_HOST'],
        database=app.config['DB_NAME']
    )

@Index.route('/test_db_connection')
def test_db():  
    try:
        # Intentar establecer una conexión y realizar una operación simple en la base de datos
        connection = connect_to_database()
        cursor = connection.cursor() # El cursor se utiliza para ejecutar comandos SQL en la base de datos.
        cursor.execute("SELECT 1") # Ejecución de SQL
        result = cursor.fetchone() # Se utiliza el método fetchone() para recuperar el resultado de la consulta
        message = f"La conexión a la base de datos es exitosa. Resultado: {result}" # Template literal
    except Exception as e:
        message = f"Error de conexión a la base de datos: {str(e)}"
    finally:
        cursor.close() # El cursor se finaliza
        connection.close() # Se finaliza la conexión

    return jsonify({'message': message}) # respuesta en formato json

app/Index/templates/index.html
<!-- Use it like any other HTML element -->

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('Index.static', filename='main.css') }}">
</head>

<body>

  <section class="section-products">
    <span data-bs-custom-class="custom-tooltip" tabindex="0" data-bs-toggle="tooltip" data-bs-placement="top"
      data-bs-title="Click para agregar un nuevo producto">
      <a href="/agregar_producto" class="btn .bg-secondary " style="width: 100%; font-size: 2rem;"> ➕</a>
    </span>

    <div class="container">
      <div class="row justify-content-center text-center">
        <div class="col-md-8 col-lg-6">
          <div class="header">
            <h1>Productos</h1>
          </div>
        </div>
      </div>
      <div class="row">
        {% for archivo in img_url %}
        <!-- Single Product -->
        <div class="col-md-6 col-lg-4 col-xl-3">
          <div id="product-1" class="single-product">
            <div class="part-1"
              style="background: url('{{ archivo.RutaImagen }}') no-repeat center; background-size: cover;">
              <ul>
                <li><a href="/detalle_producto/{{ archivo.Id }}" class="btn btn-primary">Ver Mas</a></li>
                <span data-bs-custom-class="custom-tooltip" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-title="Click para eliminar el producto">
                  <li>
                    <a href="{{ url_for('Index.borrar_producto', producto_id=archivo.Id) }}"
                      class="btn btn-danger">✖</a>
                  </li>
                </span>
                <span data-bs-custom-class="custom-tooltip" data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="Click para editar el producto">
                <li><a href="{{ url_for('Index_Modificar.actualizar_producto', producto_id=archivo.Id) }}"
                    class="btn btn-danger">⚙</a></li>
                </span>
              </ul>
            </div>
            <div class="part-2">
              <h3 class="product-title">{{ archivo.NombreProducto }}</h3>
              <h4 class="product-price">${{ archivo.Precio }}</h4>
              <!-- Agrega cualquier otra información dinámica que desees mostrar -->
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </section>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>
  <script>
    const tooltipTriggerList = document.querySelectorAll(
      '[data-bs-toggle="tooltip"]'
    );
    const tooltipList = [...tooltipTriggerList].map(
      (tooltipTriggerEl) => new bootstrap.Tooltip(tooltipTriggerEl)
    );
  </script>
</body>

</html>