app/Create/__init__.py
from flask import Blueprint


Index_create = Blueprint('Index_create', __name__, template_folder='templates', static_folder='static')

from . import routes

app/Create/routes.py
from . import Index_create
import os
import secrets
from flask import render_template, redirect, url_for, request, jsonify, current_app
from werkzeug.utils import secure_filename
from werkzeug.datastructures import  FileStorage
import requests
from ..config import DevelopmentConfig
import mysql.connector

# Función para conectar a la base de datos
def connect_to_database():
    from .. import app
    return mysql.connector.connect(
        user=app.config['DB_USER'],
        password=app.config['DB_PASSWORD'],
        host=app.config['DB_HOST'],
        database=app.config['DB_NAME']
    )

@Index_create.route('/crear_producto', methods=['GET'])
def index():
    categorias = []

    try:
        # Intentar establecer una conexión y realizar una operación simple en la base de datos
        connection = connect_to_database()
        cursor = connection.cursor() 
        cursor.execute("SELECT * FROM Categorias;") 
        results = cursor.fetchall() 
        for result in results:
            categorias.append({
                'Id': result[0],
                'NombreCategoria': result[1]
            })
    except Exception as e:
        print(str(e))
        categorias.append('error')
    finally:
        cursor.close()
        connection.close()
    return render_template('crear_producto.html', categorias=categorias)

@Index_create.route('/agregar_producto', methods=['GET','POST'])
def agregar_producto():

    if request.method != 'POST':
        return redirect('/crear_producto')

    nombre = request.form['nombre']
    precio = float(request.form['precio'])
    descripcion = request.form['descripcion']
    ref = request.form['ref']
    categorias = request.form.getlist('categorias[]')


    # Carpeta para guardar las imágenes
    img_folder = os.path.join(current_app.config['APP_FOLDER'], current_app.config['ASSETS_FOLDER'], 'img')
    os.makedirs(img_folder, exist_ok=True)

    # Carpeta para guardar los modelos 3D
    models_folder = os.path.join(current_app.config['APP_FOLDER'], current_app.config['ASSETS_FOLDER'], 'models')
    os.makedirs(models_folder, exist_ok=True)



    # Guardar imágenes
    imagenes = []
    for imagen in request.files.getlist('imagenes[]'):
        filename = secrets.token_hex(16) + secure_filename(imagen.filename)
        img_path = os.path.join(img_folder, filename)
        imagen.save(img_path)
        imagenes.append(filename)
    
    # Guardar modelos 3D
    asset = None
    if 'asset' in request.files and request.files['asset']:
        modelo = request.files['asset']
        filename = secrets.token_hex(16) + secure_filename(modelo.filename)
        model_path = os.path.join(models_folder, filename)
        modelo.save(model_path)
        print(model_path)
        asset = filename


    # Conectar a la base de datos
    connection = connect_to_database()
    cursor = connection.cursor()

    try:
        # Insertar el nuevo producto en la tabla Productos
        if asset is None:
            cursor.execute(
                "INSERT INTO Productos (Nombre, Precio, Descripcion, Ref) VALUES (%s, %s, %s, %s)",
                (nombre, precio, descripcion, ref)
            )
        else:
            asset_path = "models/{}".format(asset)
            cursor.execute(
                "INSERT INTO Productos (Nombre, Precio, Descripcion, Ref, Asset) VALUES (%s, %s, %s, %s, %s)",
                (nombre, precio, descripcion, ref, asset_path)
            )

        product_id = cursor.lastrowid # Obtener el ID del producto insertado
        print(product_id)
        # Insertar las categorías en la tabla Categorias_de_Productos
        for categoria_id in categorias:
            cursor.execute(
                "INSERT INTO Categorias_de_Productos (Id_Categoria, Id_Productos) VALUES (%s, %s)",
                (categoria_id, product_id)
            )

        # Insertar las imágenes en la tabla Imagenes_de_Productos
        for img_filename in imagenes:
            img_path = "img/{}".format(img_filename)
            cursor.execute(
                "INSERT INTO Imagenes (Img) VALUES (%s)",
                (img_path,)
            )
            img_id = cursor.lastrowid
            cursor.execute(
                "INSERT INTO Imagenes_de_Productos (Id_Img, Id_Productos) VALUES (%s, %s)",
                (img_id, product_id)
            )

        # Commit para guardar los cambios en la base de datos
        connection.commit()

    except Exception as e:
        print(f"Error al insertar en la base de datos: {str(e)}")
        # Manejar el error como desees

    finally:
        # Cerrar la conexión
        cursor.close()
        connection.close()
    
    return redirect('/crear_producto')

app/Create/templates/crear_producto.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Agregar Producto</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
</head>

<body style="margin: 0 auto; padding: 0;">
  <div class="container-fluid d-flex flex-wrap justify-content-center align-item-center flex-column gap-2"
    style="width: 100%; height: 98vh">
    <div class="container-fluid p-4" style="background-color: #adb5bd; color: #ffffff;">
      <form method="post" action="{{ url_for('Index_create.agregar_producto') }}" enctype="multipart/form-data">
        <div class="input-group mb-3">
          <span class="input-group-text" for="nombre" id="inputGroup-sizing-default">Nombre</span>
          <input type="text" name="nombre" class="form-control" required aria-label="Sizing example input"
            aria-describedby="inputGroup-sizing-default" />
        </div>

        <div class="input-group mb-3">
          <span class="input-group-text" for="precio" id="inputGroup-sizing-default">Precio</span>
          <input type="text" name="precio" class="form-control" required aria-label="Sizing example input"
            aria-describedby="inputGroup-sizing-default" />
        </div>

        <div class="input-group mb-3">
          <span class="input-group-text" for="descripcion" id="inputGroup-sizing-default">Descripción</span>
          <textarea type="text" rows="2" name="descripcion" class="form-control" required
            aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default"></textarea>
        </div>

        <div class="input-group mb-3">
          <span class="input-group-text" for="ref" id="inputGroup-sizing-default">Referencia</span>
          <input type="text" name="ref" class="form-control" required aria-label="Sizing example input"
            aria-describedby="inputGroup-sizing-default" />
        </div>

        <label for="categorias">Categorías:</label>
        <select name="categorias[]" class="form-select" multiple aria-label="Multiple select example"
          data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Usa la tecla Ctrl para selecionar multiples">
          {% for categoria in categorias %}
          <option value="{{ categoria.Id }}">
            <span class="d-inline-block" tabindex="0">
              {{ categoria.NombreCategoria }}
            </span>
          </option>
          {% endfor %}
        </select>

        <div class="mb-3">
          <label for="imagenes" class="form-label">Imágenes (selecciona múltiples)</label>
          <input class="form-control" type="file" name="imagenes[]" accept="image/*" multiple />
        </div>

        <div class="mb-3">
          <label for="asset" class="form-label">Asset (Opcional)</label>
          <input class="form-control" type="file" name="asset" accept=".glb" />
        </div>
        <div class="col-12 d-flex gap-2">
          <div class="">
            <button type="submit" class="btn btn-light">Enviar</button>
          </div>
          <div class="">
            <a href="/" class="btn btn-danger">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>
  <script>
    const tooltipTriggerList = document.querySelectorAll(
      '[data-bs-toggle="tooltip"]'
    );
    const tooltipList = [...tooltipTriggerList].map(
      (tooltipTriggerEl) => new bootstrap.Tooltip(tooltipTriggerEl)
    );
  </script>
</body>

</html>